# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ats.proto for package 'ats'

require 'grpc'
require 'ats_pb'

module Ats
  module AtsService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'ats.AtsService'

      rpc :CheckRecruiter, ::Ats::CheckRecruiterRequest, ::Ats::CheckRecruiterResponse
    end

    Stub = Service.rpc_stub_class
  end
end
