# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ats.proto

require 'google/protobuf'


descriptor_data = "\n\tats.proto\x12\x03\x61ts\"*\n\x15\x43heckRecruiterRequest\x12\x11\n\tmember_id\x18\x01 \x01(\t\".\n\x16\x43heckRecruiterResponse\x12\x14\n\x0cis_recruiter\x18\x01 \x01(\x08\x32Y\n\nAtsService\x12K\n\x0e\x43heckRecruiter\x12\x1a.ats.CheckRecruiterRequest\x1a\x1b.ats.CheckRecruiterResponse\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Ats
  CheckRecruiterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ats.CheckRecruiterRequest").msgclass
  CheckRecruiterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ats.CheckRecruiterResponse").msgclass
end
